# 代理服务器配置
[server]
# 本地监听地址和端口
host = "127.0.0.1"
port = 3000

# 目标服务器配置
[target]
# 目标服务器地址
host = "172.88.22.12"
port = 8383
protocol = "https"

# 代理路径配置
[proxy]
# 代理路径前缀
path_prefix = "/federatio"

# 请求配置
[request]
# 请求超时时间（秒）
timeout = 120
# 是否接受无效证书（仅用于开发环境）
accept_invalid_certs = true

# 日志配置
[log]
# 日志级别: error, warn, info, debug, trace
level = "info"
